# Визуализация опухолей прямой кишки при КТ

Патогномоничным признаком опухолевого поражения является утолщение стенки прямой кишки более 5 мм при адекватном растяжении просвета кишки. Опухолевая ткань характеризуется неоднородной плотностью и умеренным контрастным усилением. Инфильтрация периректальной клетчатки проявляется появлением тяжистых изменений и узелковых структур, что указывает на распространение процесса за пределы стенки кишки.

Диагностическая ценность локального утолщения стенки во многом зависит от того как проводилось исследование с раздутванием кишки или без. Это обусловлено трудностью дифференцировки утолщения обусловленного опухолью от физиологического утолщения стенки и воспалительных изменений. В отличии от МРТ  при КТ довольно ограничены возможности в дифференцироваке слоев. Тем не менее при раздувании предсказательная ценность утолщения стенки кишки имеет положительную предсказательную ценность 92%. В совокупности с другими критериями точность может достигать до 98% [@galComputerizedTomographyCriteria2020]. 

При наличии только одного из признаков опухоли, следует сопоставлять результаты КТ с другими методами исследования.