<!-- markdownlint-disable MD041 -->

## Т-стадирование

Оценка глубины инвазии опухоли (T-категория)--один из ключевых параметров при стадировании рака прямой кишки. Именно она определяет возможность радикального хирургического вмешательства, необходимость проведения неоадъювантной химиолучевой терапии (ХЛТ) и прогноз локального контроля. Например, при опухолях с глубокой инвазией в мезоректальную клетчатку (Т3с--d), поражением брюшины (T4a) или инвазией в соседние органы (T4b) значительно возрастает риск местного рецидива и отдалённого метастазирования. Кроме того, градация внутри Т3-категории по глубине экстрамуральной инвазии позволяет более точно прогнозировать течение болезни и дифференцировать показания к ХЛТ.

### Общие принципы лучевой диагностики

T-категория в классификации TNM отражает степень инвазии опухоли в стенку прямой кишки и окружающие ткани (см. таблицу 1 в разделе @src/Rectal-Cancer-Staging.qmd).

При описании необходимо определить наиболее инвазивную часть опухоли (опухолевую площадку), соответствующую области наибольшей глубины инфильтрации, которая обычно расположена в центральных отделах опухоли. Оценка глубины распространения за пределы кишечной стенки при раке нижнеампулярного отдела представляет определённые сложности из-за сужения мезоректальной клетчатки [@shihabCanNovelMRI2011, @nikolouzakisDetailedAppliedAnatomy2019]. Эти характеристики позволяют уточнить потенциальную резектабельность, риск и уровень инвазии мезоректальной фасции. Методика измерения глубины инвазии представлена на @fig:t-staging-depth-measurement.

Установлено, что МРТ и КТ не обладают достаточной точностью в определении минимальной инвазии кишечной стенки, за исключением некоторых случаев, когда на МРТ можно отчетливо дифференцировать и проследить сохраненный подслизистый слой (гиперинтенсивный МР-сигнал) в основании опухоли. В связи с этим, рекомендуемым методом для точного определения Т1-Т2 опухолей является эндоректальное ультразвуковое исследование из-за его высокой диагностической эффективности в оценке данных образований [7].

При распространении опухоли за пределы стенки кишки обязательным является измерение глубины инвазии от наружного края мышечной стенки до дистальной точки опухоли (@fig:t-staging-depth-measurement). Cогласно последней версии клинических рекомендаций,необходимо стратифицировать категорию Т3 в зависимости от глубины инвазии клетчатки, и указывать глубину экстрамурального распространения в миллиметрах в заключении (@fig:t3-stratification).

- **T3a**-- <1 мм,
- **T3b**-- 2--5 мм,
- **T3c**-- 6--15 мм,
- **T3d**-- >15 мм .

Стратификация T3 важна, поскольку глубина экстрамуральной инвазии напрямую коррелирует с 5-летней выживаемостью: 85% при ≤5 мм против 54% при >5 мм [22].

### МРТ

МРТ является основным методом визуализации для оценки T-категории при РПК. Оценка глубины инвазии осуществляется на высокоразрешающих косоаксиальных Т2-ВИ, строго перпендикулярных к длинной оси опухоли, на которых можно оценить структуру слоев стенки кишки и распространение опухоли за её пределы (@fig:t-staging-depth-measurement, @fig:t1-t2-staging). Диагностическая точность, чувствительность и специфичность ВР-МРТ прямой кишки при оценке категории-Т составляют 85%, 87% и 75% соответственно [4].

:::{#fig:t-staging-depth-measurement} Измерение глубины инвазии в мезоректум{#fig:t-staging-depth-measurement-1 width=90%}

Измерение глубины экстрамуральной инвазии опухоли прямой кишки. МРТ, Т2-взвешенные изображения высокого разрешения (толщина среза 3 мм), ориентированные строго перпендикулярно к длинной оси опухоли на уровне максимальной инвазии. Методика измерения: от наружного края мышечного слоя стенки кишки до наиболее удаленной точки опухолевой инвазии в мезоректальную клетчатку.**А**- опухоль среднеампулярного отдела прямой кишки с узловым типом экстрамурального распространения, глубина инвазии 4 мм, категория Т3b согласно стратификации TNM;**Б**- опухоль нижнеампулярного отдела прямой кишки с массивным экстрамуральным компонентом, глубина инвазии 10 мм, категория Т3d. Маркеры: пунктирная линия - наружный контур мышечного слоя стенки кишки; двунаправленная стрелка - измерение глубины инвазии. :::

#### T1

При T1-опухолях инвазия ограничивается слизистой и подслизистой оболочками.

Гиперинтенсивный подслизистый слой на Т2-ВИ четко отделяет опухоль от гипоинтенсивного мышечного слоя, что указывает на T1-стадию[@brown2003preoperative] (@fig:t1-t2-staging).

МРТ позволяет выявлять T1-опухоли с точностью 85% при использовании высокоразрешающих последовательностей[@bipat2004rectal]. Однако разрешающая способность МРТ не всегда позволяет дифференцировать минимальную степень инвазии, и в этих случаях предпочтительнее использовать эндоректальное УЗИ [7].

#### T2

T2-опухоли характеризуются гипоинтенсивным сигналом опухоли, проникающим до, но не за пределы мышечного слоя. На МРТ мышечная оболочка определяется как гипоинтенсивная полоска, часто с двумя слоями -- циркулярным и продольным. Отсутствие признаков выхода опухоли в мезоректум--диагностический критерий T2 (@fig:t1-t2-staging).

:::{#fig:t1-t2-staging}

ВР-МРТ, Т2-ВИ опухоль категории Т1

{#fig:t1-t2-staging-1 width=48%}

ВР-МРТ, Т2-ВИ опухоль категории Т2

{#fig:t1-t2-staging-2 width=48%}

Дифференциальная диагностика ранних стадий рака прямой кишки. Высокоразрешающая МРТ, Т2-взвешенные изображения (толщина среза 3 мм, матрица 256×256), ориентированные перпендикулярно к длинной оси опухоли.**А**- Опухоль среднеампулярного отдела прямой кишки категории Т1: инвазия ограничена подслизистым слоем, гиперинтенсивный сигнал подслизистой оболочки сохранен и четко отделяет опухоль от интактного гипоинтенсивного мышечного слоя, толщина мышечного слоя 2-3 мм;**Б**- Опухоль нижнеампулярного отдела прямой кишки категории Т2: полная инвазия подслизистого слоя с вовлечением мышечного слоя, гиперинтенсивный сигнал подслизистой оболочки прослеживается фрагментарно, опухоль проникает в мышечный слой, но не выходит за его пределы, наружный контур мышечного слоя четкий. Маркеры: белые стрелки - гипоинтенсивный мышечный слой; черные стрелки - гиперинтенсивный подслизистый слой; звездочка - изоинтенсивная опухолевая ткань. :::

#### T3

T3 устанавливается при наличии экстрамурального компонента опухоли за пределами мышечной оболочки. На Т2-ВИ он выглядит как сигнал средней интенсивности, распространяющийся в мезоректальную клетчатку. Примеры различных степеней стратификации T3 опухолей представлены на @fig:t3-stratification.

:::{#fig:t3-stratification}

ВР-МРТ, Т2-ВИ опухоль категории Т3b

{#fig:t3-stratification-1 width=32%}

ВР-МРТ, Т2-ВИ опухоль категории Т3d

{#fig:t3-stratification-2 width=32%}

КТ, опухоль категории T3c

{#fig:t3-stratification-3 width=32%}

Стратификация T3 опухолей по глубине инвазии:**А**- ВР-МРТ, Т2-ВИ по короткой оси опухоли прямой кишки. Категории Т3b (глубина инвазии мезоректума 4мм);**Б**- ВР-МРТ, Т2-ВИ по длинной оси опухоли прямой кишки. Категории Т3d (глубина инвазии мезоректума 21мм);**В**- аксиальный срез КТ портальная фаза сканирования. Категория T3c (глубина инвазии мезоректума 10мм). :::

Выделяют узловое и спикулообразное экстрамуральное распространение опухоли.

Последнее сложно дифференцировать с перитуморальной десмопластической реакцией (@fig:t2-desmoplastic-reaction), для этого используют следующие критерии оценки:

На**Т2-ВИ**

- Опухолевая ткань: сигнал имеет средней интенсивности на Т2-ВИ.
- Десмопластическая реакция: гипоинтенсивные спикулы на Т2-ВИ.

На**DWI**

- Опухоль демонстрирует ограничение диффузии.
- Десмопластическая реакция не ограничивает диффузию, поскольку соответствует фиброзной ткани.

DWI более надёжна в дифференциальной диагностике опухоли и фиброза по сравнению с контрастным усилением, так как даже фиброзные спикулы могут накапливать парамагнетик спикулы (@fig:t2-desmoplastic-reaction) [9].

При обнаружении спикул в мезоректальной клетчатке такие изменения рекомендуется расценивать как возможную минимальную инвазию--T2/T3a (@fig:t2-desmoplastic-reaction). Чёткое разграничение этих стадий не столь важно, поскольку минимальная инвазия в мезоректум (<1 мм) при Т3а может не требовать ХЛТ в ряде случаев, аналогично Т2-опухолям [9].

:::{#fig:t2-desmoplastic-reaction}

МРТ Т2-ВИ аксиальная плоскость

{#fig:t2-desmoplastic-reaction-1 width=48%}

МРТ Т1-ВИ с контрастированием

{#fig:t2-desmoplastic-reaction-2 width=48%}

ДВИ (b=800) аксиальная плоскость

{#fig:t2-desmoplastic-reaction-3 width=48%}

ИКД-карты аксиальная плоскость

{#fig:t2-desmoplastic-reaction-4 width=48%}

МРТ Т2-ВИ корональная плоскость

{#fig:t2-desmoplastic-reaction-5 width=48%}

МРТ Т2-ВИ сагиттальная плоскость

{#fig:t2-desmoplastic-reaction-6 width=48%}

Дифференциальная диагностика десмопластической реакции и истинной опухолевой инвазии при раке прямой кишки. Опухоль среднеампулярного отдела прямой кишки, категория Т2 (опухоль ограничена мышечным слоем). МРТ-исследование выполнено на томографе 1.5Т, толщина среза 3 мм.**А**- Т2-ВИ в аксиальной плоскости: десмопластическая реакция визуализируется как гипоинтенсивные спикулы, исходящие от наружного контура мышечного слоя в мезоректальную клетчатку (белые стрелки), длина спикул до 3 мм;**Б**- Т1-ВИ с жироподавлением в аксиальной плоскости, постконтрастная фаза (внутривенное введение гадолиниевого контрастного препарата): интенсивное накопление контраста в области спикул десмопластической реакции (белые стрелки), что может имитировать экстрамуральную инвазию (критерий Т3);**В**- Диффузионно-взвешенное изображение (b=800 с/мм²) в аксиальной плоскости: отсутствие ограничения диффузии в области спикул подтверждает фиброзную природу изменений, наружный контур мышечного слоя прослеживается четко без признаков истинной инвазии;**Г**- Карта измеряемого коэффициента диффузии (ИКД) в аксиальной плоскости: высокие значения ИКД в области спикул (>1.0×10⁻³ мм²/с) подтверждают отсутствие опухолевой ткани;**Д**- Т2-ВИ в корональной плоскости: дополнительная визуализация спикулообразных изменений для оценки их протяженности;**Е**- Т2-ВИ в сагиттальной плоскости: визуализация опухоли по длинной оси для оценки краниокаудальной протяженности. Маркеры: белые стрелки - спикулы десмопластической реакции; черные стрелки - наружный контур мышечного слоя. :::

#### T4а

T4a устанавливается при инвазии брюшины. На Т2-ВИ брюшина визуализируется как тонкая гипоинтенсивная полоска <1 мм. Отсутствие прослойки жировой клетчатки между опухолью и брюшиной, нарушение её целостности, при изменении сигнала, утолщении или узловатости брюшины указывает на T4a (@fig:t4a-peritoneal-invasion). При этом простое соприкосновение с брюшиной не является критерием вовлечения. Ключевым является оценка передней стенки верхнеампулярного отдела, где брюшина чаще всего прилежит к кишке.

:::{#fig:t4a-peritoneal-invasion}

МРТ Т2-ВИ сагиттальная плоскость

{#fig:t4a-peritoneal-invasion-1 width=48%}

МРТ Т2-ВИ аксиальная плоскость

{#fig:t4a-peritoneal-invasion-2 width=48%}

МРТ Т2-ВИ корональная плоскость

{#fig:t4a-peritoneal-invasion-3 width=48%}

МРТ ДВИ (b=800) аксиальная плоскость

{#fig:t4a-peritoneal-invasion-4 width=48%}

Инвазия переходной складки тазовой брюшины при раке прямой кишки - категория Т4а. Опухоль верхнеампулярного отдела прямой кишки с прорастанием в переходную складку брюшины. МРТ-исследование выполнено на томографе 1.5Т, толщина среза 3-4 мм.**А**- Т2-ВИ в сагиттальной плоскости: опухоль верхнеампулярного отдела прямой кишки (12 см от анального края) с нарушением целостности переходной складки брюшины (белая стрелка), утолщение и узловатость брюшины в месте контакта с опухолью, отсутствие жировой прослойки между опухолью и брюшиной, протяженность опухоли 45 мм;**Б**- Т2-ВИ в аксиальной плоскости на уровне максимальной инвазии: V-образная переходная складка брюшины с признаками опухолевой инвазии по передней стенке кишки (белая стрелка), прерывистость гипоинтенсивной линии брюшины, экстрамуральная инвазия до 8 мм;**В**- Т2-ВИ в корональной плоскости: визуализация латерального распространения опухоли и взаимоотношения с боковыми листками брюшины, подтверждение инвазии брюшины;**Г**- Диффузионно-взвешенное изображение (b=800 с/мм²) в аксиальной плоскости: выраженное ограничение диффузии в области опухоли и зоне инвазии брюшины, подтверждающее наличие жизнеспособной опухолевой ткани. Маркеры: белая стрелка - место инвазии переходной складки брюшины; черные стрелки - интактные участки брюшины; звездочка - основная опухолевая масса. :::

#### T4b

Включает поражение: органов малого таза (матки, яичников, влагалища, предстательной железы, семенных пузырьков, мочевого пузыря, мочеточников, костей и скелетных/поперечно-полосатых мышечных структур, таких как запирательная, грушевидная, седалищно-копчиковая, мышца, поднимающая задний проход, и лобково-прямокишечная мышцы), а также наружный сфинктер (вовлечение внутреннего сфинктера относится к категории Т3).

Ряд консенсусов рекомендует дополнительно включать: непрямокишечные сосуды, седалищный или крестцовый нервы, крестцово-остистые/крестцово-бугристые связки и мягкие ткани за пределами мезоректума, такие как жировая ткань запирательной, подвздошной или седалищно-прямокишечной области.

Стадия Т4b выставляется при отсутствии жировой прослойки, а также замещении структуры соседнего органа опухолевым МР-сигналом.

Выделяются три варианта отсутствия или наличия предполагаемой степени инвазии [18]:

1. **Без инвазии**--жировая прослойка чётко видна между опухолью и органом,
2. **Возможная инвазия**--прослойка не визуализируется, но нет сигнала опухоли в органе,
3. **Явная инвазия**--отсутствует жировая клетчатка между опухолью и прилежащим органом, и имеется замещение его структуры за счет участков с МР-сигналом соответствующим опухолевой ткани.

### КТ

Эффективность КТ в определении глубины инвазии опухоли прямой кишки составляет в среднем 73-80% [@ippolito2016RectalCancerStaging]. Мультипланарная реконструкция повышает точность до 86-87% по сравнению с использованием только аксиальных изображений [@ahmetogluMDCTMultiplanarReconstruction2011, @ippolito2016RectalCancerStaging, @sinhaDignosticValueMultidetector2006].

Для оптимальной оценки T стадии рекомендуется: использование тонких срезов (2-5 мм), выполнение мультипланарных реконструкций, ориентированных параллельно и перпендикулярно оси опухоли, внутривенное контрастирование с быстрым введением болюса контраста (≤3 мл/сек) [@ahmetogluMDCTMultiplanarReconstruction2011, @bartonUtilityRoutinePreoperative2002, @kijima2014PreoperativeEvaluationColorectal].

#### Т 1-2

Подслизистый слой при КТ имеет низкую плотность, так как содержит много жира.

Для оценки инвазии мышечного слоя требуется определить инфильтрирован ли подслизистый слой на уровне опухолевой площадки. Часто уверенно определить это невозможно, так эта процедура требует уверенной визуализации небольшой опухоли и отграничение ее от неизменной слизистой, определения подслизистого слоя и исключения иных причин его истончения и деформации (расширение кишки, втяжение стенки полипом).

Существуют косвенные критерии инвазии мышечного слоя основанные на размерах опухоли: для глубины инвазии Т1 поражается менее 1/2 окружности, а при Т2 более 1/2 окружности с трапециевидной деформацией стенки.

Как правило, дифференциальный диагноз Т1-2 опухолей на основании КТ данных нецелесообразен.

Наружный контур стенки и параректальная клетчатка, как правило, не изменены. Однако, и паратуморальный отек и десмопластическая реакция могут вызвать появление спикул или тяжистого уплотнение клетчатки. Такие изменения требуется дифференцировать с Т3 глубиной инвазии.

#### Т3

Появление неровности наружного контура стенки кишки на уровне опухоли говорит о распространении опухоли за пределы ее стенки.

Иногда опухоль распространяется в виде спикулообразных или тяжистых изменений.

КТ не позволяет категорично судить о природе спикулообразных изменений. Основной причиной ложноположительных результатов является перитуморальное воспаление и десмопластическая реакция вокруг опухоли. Эти изменения затрудняют дифференциацию опухолевой инфильтрации от реактивных изменений, особенно при разграничении T2 и T3 стадий [@ahmetogluMDCTMultiplanarReconstruction2011, @ippolito2016RectalCancerStaging, @kijima2014PreoperativeEvaluationColorectal, @sinhaDignosticValueMultidetector2006].

#### Т4

При глубине инвазии Т4 отмечается облитерация жировой прослойки между опухолью и прилежащими органами с явной инвазией в соседние органы и структуры [@ahmetogluMDCTMultiplanarReconstruction2011, @kijima2014PreoperativeEvaluationColorectal, @sinhaDignosticValueMultidetector2006].

Основной причиной ложноотрицательных результатов является микроскопическая инфильтрация параректальной клетчатки, невидимая на КТ. При несоответствии оси опухоли плоскости сканирования частичный объемный эффект может затруднять визуализацию наружного контура стенки. Диагностическая эффективность значительно снижается при деформации стенки кишки из-за трудности дифференциации между изгибом стенки и опухолевой инвазией [@ahmetogluMDCTMultiplanarReconstruction2011, @romanoIntrarectalUltrasoundComputed1985, @sinhaDignosticValueMultidetector2006].

Для глубоко прорастающих опухолей (Т3-Т4) КТ и МРТ имеют сопоставимую точность, в то время как для ранних стадий (Т1-Т2) МРТ превосходит КТ. [@bipatRectalCancerLocal2004, @alsukhniDiagnosticAccuracyMRI2012, @mathurComparisonCTMRI2003, @zerhouniCTMRImaging1996].
