# Список литературы

1. Гришко П. Ю., Мищенко А. В., Ивко О. В. Возможности мультипараметрической магнитно-резонансной томографии в оценке эффективности неоадъювантного лечения рака прямой кишки // Лучевая диагностика и терапия. 2019. № 4 (10). С. 49–56.

2. Каприн А. Д., Старинский В. В., Шахзадова А. О. Злокачественные новообразования в России в 2021 году (заболеваемость и смертность). М.: ФГБУ «МНИОИ им. П. А. Герцена» Минздрава России, 2022. 252 с.

3. Ale Ali H. [и др.]. Extramural venous invasion in rectal cancer: overview of imaging, histopathology, and clinical implications // Abdominal Radiology (New York). 2019. № 1 (44). С. 1–10.

4. Al-Sukhni E. [и др.]. Diagnostic accuracy of MRI for assessment of T category, lymph node metastases, and circumferential resection margin involvement in patients with rectal cancer: a systematic review and meta-analysis // Annals of Surgical Oncology. 2012. № 7 (19). С. 2212–2223.

5. Amin M. B. [и др.]. The Eighth Edition AJCC Cancer Staging Manual: Continuing to build a bridge from a population-based to a more "personalized" approach to cancer staging // CA: a cancer journal for clinicians. 2017. № 2 (67). С. 93–99.

6. Battersby N. J. [и др.]. Prospective Validation of a Low Rectal Cancer Magnetic Resonance Imaging Staging System and Development of a Local Recurrence Risk Stratification Model: The MERCURY II Study // Annals of Surgery. 2016. № 4 (263). С. 751–760.

7. Beets-Tan R. G. H. [и др.]. Magnetic resonance imaging for clinical management of rectal cancer: Updated recommendations from the 2016 European Society of Gastrointestinal and Abdominal Radiology (ESGAR) consensus meeting // European Radiology. 2018. № 4 (28). С. 1465–1475.

8. Benson A. B. [и др.]. Colon Cancer, Version 3.2024, NCCN Clinical Practice Guidelines in Oncology // Journal of the National Comprehensive Cancer Network: JNCCN. 2024. № 2D (22). С. e240029.

9. Brown G. [и др.]. Preoperative assessment of prognostic factors in rectal cancer using high-resolution magnetic resonance imaging // The British Journal of Surgery. 2003. № 3 (90). С. 355–364.

10. Chand M. [и др.]. Extramural venous invasion is a potential imaging predictive biomarker of neoadjuvant treatment in rectal cancer // British Journal of Cancer. 2014. № 1 (110). С. 19–25.

11. Heald R. J., Ryall R. D. Recurrence and survival after total mesorectal excision for rectal cancer // Lancet (London, England). 1986. № 8496 (1). С. 1479–1482.

12. Huxley R. R. [и др.]. The impact of dietary and lifestyle risk factors on risk of colorectal cancer: a quantitative overview of the epidemiological evidence // International Journal of Cancer. 2009. № 1 (125). С. 171–180.

13. Jhaveri K. S. [и др.]. MRI Detection of Extramural Venous Invasion in Rectal Cancer: Correlation With Histopathology Using Elastin Stain // AJR. American Journal of Roentgenology. 2016. № 4 (206). С. 747–755.

14. Johns L. E., Houlston R. S. A systematic review and meta-analysis of familial colorectal cancer risk // The American Journal of Gastroenterology. 2001. № 10 (96). С. 2992–3003.

15. Kikuchi R. [и др.]. Management of early invasive colorectal cancer. Risk of recurrence and clinical guidelines // Diseases of the Colon and Rectum. 1995. № 12 (38). С. 1286–1295.

16. Kim T.-H. [и др.]. The Diagnostic Performance of MRI for Detection of Extramural Venous Invasion in Colorectal Cancer: A Systematic Review and Meta-Analysis of the Literature // AJR. American Journal of Roentgenology. 2019. № 3 (213). С. 575–585.

17. KSAR Study Group for Rectal Cancer. Essential Items for Structured Reporting of Rectal Cancer MRI: 2016 Consensus Recommendation from the Korean Society of Abdominal Radiology // Korean Journal of Radiology. 2017. № 1 (18). С. 132–151.

18. Lalwani N. [и др.]. Baseline MR Staging of Rectal Cancer: A Practical Approach // Seminars in Roentgenology. 2021. № 2 (56). С. 164–176.

19. MERCURY Study Group. Extramural depth of tumor invasion at thin-section MR in patients with rectal cancer: results of the MERCURY study // Radiology. 2007. № 1 (243). С. 132–139.

20. Messenger D. E., Driman D. K., Kirsch R. Developments in the assessment of venous invasion in colorectal cancer: implications for future practice and patient outcome // Human Pathology. 2012. № 7 (43). С. 965–973.

21. Nougaret S. [и др.]. The use of MR imaging in treatment planning for patients with rectal carcinoma: have you checked the "DISTANCE"? // Radiology. 2013. № 2 (268). С. 330–344.

22. Quirke P., Williams G. Minimum dataset for colorectal cancer histopathology reports. 2000.

23. Raskov H. [и др.]. Colorectal carcinogenesis – update and perspectives // World Journal of Gastroenterology. 2014. № 48 (20). С. 18151–18164.

24. Rasool S. [и др.]. A comparative overview of general risk factors associated with the incidence of colorectal cancer // Tumour Biology: The Journal of the International Society for Oncodevelopmental Biology and Medicine. 2013. № 5 (34). С. 2469–2476.

25. Salerno G. V. [и др.]. Magnetic resonance imaging prediction of an involved surgical resection margin in low rectal cancer // Diseases of the Colon and Rectum. 2009. № 4 (52). С. 632–639.

26. Shihab O. C. [и др.]. Patients with low rectal cancer treated by abdominoperineal excision have worse tumors and higher involved margin rates compared with patients treated by anterior resection // Diseases of the Colon and Rectum. 2010. № 1 (53). С. 53–56.

27. Shihab O. C. [и др.]. Can a novel MRI staging system for low rectal cancer aid surgical planning? // Diseases of the Colon and Rectum. 2011. № 10 (54). С. 1260–1264.

28. Stoner R. C., Korngold E. K. Anatomy of Pelvic Lymph Nodal Stations and Their Role in Staging of Rectal Cancers // Seminars in Roentgenology. 2021. № 2 (56). С. 152–157.

29. Taylor F. G. M. [и др.]. One millimetre is the safe cut-off for magnetic resonance imaging prediction of surgical margin status in rectal cancer // The British Journal of Surgery. 2011. № 6 (98). С. 872–879.

30. Taylor F. G. M. [и др.]. Preoperative magnetic resonance imaging assessment of circumferential resection margin predicts disease-free survival and local recurrence: 5-year follow-up results of the MERCURY study // Journal of Clinical Oncology: Official Journal of the American Society of Clinical Oncology. 2014. № 1 (32). С. 34–43.

31. Tenesa A., Dunlop M. G. New insights into the aetiology of colorectal cancer from genome-wide association studies // Nature Reviews. Genetics. 2009. № 6 (10). С. 353–358.

32. Wnorowski A. M. [и др.]. Mucin-Containing Rectal Carcinomas: Overview of Unique Clinical and Imaging Features // AJR. American Journal of Roentgenology. 2019. № 1 (213). С. 26–34.

33. Yu S. K. T. [и др.]. Magnetic resonance imaging defined mucinous rectal carcinoma is an independent imaging biomarker for poor prognosis and poor response to preoperative chemoradiotherapy // European Journal of Cancer (Oxford, England: 1990). 2014. № 5 (50). С. 920–927.

34. Zhang H. [и др.]. Chemical shift effect predicting lymph node status in rectal cancer using high-resolution MR imaging with node-for-node matched histopathological validation // European Radiology. 2017. № 9 (27). С. 3845–3855.

35. Nikolouzakis T. K. [и др.]. Detailed and applied anatomy for improved rectal cancer treatment // Annals of Gastroenterology. 2019. № 5 (32). С. 431–440.

36. Клинические рекомендации «Рак прямой кишки», одобренные научным советом МЗ РФ. 2023.
