# Стадирование рака прямой кишки

Стадирование -- важнейший этап диагностики, позволяющий оценить распространённость опухоли и определить тактику лечения. Оно влияет на стратификацию пациентов, выбор объёма операции и показания к неоадъювантной терапии.

Особая важность стадирования обусловлена тем, что на момент первичной диагностики пациенты могут иметь как локализованные формы заболевания, так и отдалённые метастазы, что кардинально меняет лечебный подход -- от малоинвазивных и сфинктеросохраняющих операций до неоадъювантной химиолучевой терапии.

Ключевое значение имеет и точная анатомическая локализация опухоли: она определяет хирургический доступ, возможность выполнения резекций и сохранения сфинктера. Критичными являются расстояние до зубчатой линии и расположение относительно переходной складки тазовой брюшины. Для опухолей нижнеампулярного отдела необходимо уточнение инвазии в сфинктерный аппарат и *m. levator ani*, что позволяет определить возможность выполнения межсфинктерной резекции.

Вовлечение мезоректальной фасции, поражение лимфоузлов и наличие экстрамуральной венозной инвазии (EMVI) определяет необходимость расширенных вмешательств, включая латеральную лимфодиссекцию, и объём лучевой терапии.

Определение морфологических особенностей образования, например муцинозная структура или перстневидноклеточный рак, позволяют предположить потенциально худший прогноз, в связи с большим риском метахронных метастазов и худшим ответом на химиолучевую терапию.

Таким образом, качественное стадирование и точная топографическая оценка формируют основу персонализированного лечения, снижая риск рецидива и повышая шансы на функционально щадящую хирургию или безоперационное ведение пациента.


Стадирование рака прямой кишки основано на международной классификации злокачественных новообразований TNM, разработанной объединенным американским комитетом по раку (The American Joint Committee on Cancer, AJCC) и Союзом международного контроля над раковыми заболеваниями (Union for International Cancer Control, UICC) 8-го издания 2017 года (табл. 1) [5].

Классификация TNM включает три основные категории:

-   **T (tumor)** -- степень инвазии первичной опухоли в стенку кишки и за её пределы,

-   **N (nodes)** -- наличие и число метастатически поражённых регионарных лимфатических узлов,

-   **M (metastasis)** -- наличие отдалённых метастазов.

**Таблица 1** Классификация РПК по системе TNM

+-----------+------------------------------------+---------------------+
| > **Ка    | > **Описание**                     | > **Дополнительные  |
| тегория** |                                    | > подклассификации  |
|           |                                    | > с использованием  |
|           |                                    | > лучевых методов   |
|           |                                    | > диагностики**     |
+===========+====================================+=====================+
| > **TX**  | > недостаточно данных для оценки   |                     |
|           | > первичной опухоли                |                     |
+-----------+------------------------------------+---------------------+
| > **Tis** | > преинвазивный рак                |                     |
|           | > (интраэителиальная инвазия или   |                     |
|           | > инвазия собственной пластинки    |                     |
|           | > слизистой оболочки).             |                     |
+-----------+------------------------------------+---------------------+
| > **T1**  | > опухоль распространяется в       | > Подклассификация  |
|           | > подслизистый слой стенки кишки   | > по Kikuchi^1^     |
|           |                                    | >                   |
|           |                                    | > **T1sm1** --      |
|           |                                    | > глубина инвазии   |
|           |                                    | > подслизистого     |
|           |                                    | > слоя до 1/3       |
|           |                                    | >                   |
|           |                                    | > **T1sm2** --      |
|           |                                    | > глубина инвазии   |
|           |                                    | > подслизистого     |
|           |                                    | > слоя до 2/3       |
|           |                                    | >                   |
|           |                                    | > **T1sm3** --      |
|           |                                    | > полная инвазия    |
|           |                                    | > опухолью всего    |
|           |                                    | > подслизистого     |
|           |                                    | > слоя              |
+-----------+------------------------------------+---------------------+
| > **T2**  | > опухоль распространяется на      |                     |
|           | > мышечный слой                    |                     |
+-----------+------------------------------------+---------------------+
| > **T3**  | > врастание в субсерозу или        | > Подклассификация  |
|           | > неперитонизированную             | > ^2^:              |
|           | > околокишечную клетчатку          | >                   |
|           |                                    | > **T3a --**        |
|           |                                    | > инвазия в         |
|           |                                    | > мезоректальную    |
|           |                                    | > клетчатку менее 1 |
|           |                                    | > мм                |
|           |                                    | >                   |
|           |                                    | > **T3b** **--**    |
|           |                                    | > инвазия в         |
|           |                                    | > мезоректальную    |
|           |                                    | > клетчатку 1-5 мм  |
|           |                                    | >                   |
|           |                                    | > **T3c --**        |
|           |                                    | > инвазия в         |
|           |                                    | > мезоректальную    |
|           |                                    | > клетчатку 5-15 мм |
|           |                                    | >                   |
|           |                                    | > **T3d --**        |
|           |                                    | > инвазия в         |
|           |                                    | > мезоректальную    |
|           |                                    | > клетчатку более   |
|           |                                    | > 15 мм             |
+-----------+------------------------------------+---------------------+
| > **T4**  | > опухоль прорастает в окружающие  |                     |
|           | > органы и ткани или серозную      |                     |
|           | > оболочку при локализации в       |                     |
|           | > верхнеампулярном отделе прямой   |                     |
|           | > кишки                            |                     |
+-----------+------------------------------------+---------------------+
| > **T4a** | > прорастание висцеральной брюшины |                     |
+-----------+------------------------------------+---------------------+
| > **T4b** | > прорастание в другие органы и    |                     |
|           | > структуры^3,4^                   |                     |
+-----------+------------------------------------+---------------------+
| >         |                                    |                     |
| Состояние |                                    |                     |
| > ре      |                                    |                     |
| гионарных |                                    |                     |
| > лимф    |                                    |                     |
| атических |                                    |                     |
| > узлов   |                                    |                     |
+-----------+------------------------------------+---------------------+
| > **Nх**  | > Недостаточно данных для оценки   |                     |
+-----------+------------------------------------+---------------------+
| > **N0**  | > Признаков поражения регионарных  |                     |
|           | >                                  |                     |
|           | > лимфатических узлов нет          |                     |
+-----------+------------------------------------+---------------------+
| > **N1**  | > Метастазы в 1--3 (включительно)  |                     |
|           | > регионарных лимфатических узлах  |                     |
+-----------+------------------------------------+---------------------+
| > **N1a** | > метастазы в 1 регионарном        |                     |
|           | > лимфатическом узле               |                     |
+-----------+------------------------------------+---------------------+
| > **N1b** | > метастазы в 2--3 лимфатических   |                     |
|           | > узла                             |                     |
+-----------+------------------------------------+---------------------+
| > **N1c** | > диссеминаты в брыжейке без       |                     |
|           | > поражения регионарных            |                     |
|           | > лимфатических узлов              |                     |
+-----------+------------------------------------+---------------------+
| > **N2**  | > Метастазы в более чем 3-х        |                     |
|           | > регионарных лимфатических узлах  |                     |
+-----------+------------------------------------+---------------------+
| > **N2a** | > поражено 4--6 лимфатических      |                     |
|           | > узлов                            |                     |
+-----------+------------------------------------+---------------------+
| > **N2b** | > поражено 7 и более лимфатических |                     |
|           | > узлов                            |                     |
+-----------+------------------------------------+---------------------+
| > О       |                                    |                     |
| тдаленные |                                    |                     |
| >         |                                    |                     |
| метастазы |                                    |                     |
+-----------+------------------------------------+---------------------+
| > **М0**  | > отдаленных метастазов нет        |                     |
+-----------+------------------------------------+---------------------+
| > **М1**  | > наличие отдаленных метастазов    |                     |
+-----------+------------------------------------+---------------------+
| > **М1а** | > наличие отдаленных метастазов в  |                     |
|           | > одном органе                     |                     |
+-----------+------------------------------------+---------------------+
| > **M1b** | > наличие отдаленных метастазов    |                     |
|           | > более чем в одном органе         |                     |
+-----------+------------------------------------+---------------------+
| > **M1c** | > метастазы по брюшине             |                     |
+-----------+------------------------------------+---------------------+

*^1^ -- при планировании местного иссечения Т1 рака прямой кишки
проводится детальное подстадирование на основе данных ТРУЗИ. [16]*

*^2^ -- для персонализации показаний к неоадъювантному лечению Т3 рака
прямой кишки проводится детальная оценка глубины экстрамурального
распространения опухоли на основе МРТ.*

Итоговая стадия определяется комбинацией этих параметров и может обозначаться буквенно-цифровым кодом (например, cT3N1M0) или интегральной стадией (I, II, III, IV), отражающей прогноз.

Стадия фиксируется в различные моменты лечения:

-   **Клиническая стадия** (сTNM) -- устанавливается до начала лечения по результатам неинвазивных методов, включая МРТ и эндоскопию.

-   **Инструментальная стадия** (iTNM) -- подтип клинической стадии, когда стадирование выполняется с помощью методов визуализации.

-   **Патоморфологическая стадия** (pTNM) -- определяется после хирургического вмешательства и гистологического анализа препарата.

-   **Посттерапевтическая стадия** (yTNM) -- используется после проведения химио- или лучевой терапии, включает ycTNM (клиническая после терапии) и ypTNM (патоморфологическая после терапии).

Клиническая стадия не пересматривается на основании данных, полученных после начала лечения. Это правило обеспечивает корректность клинических исследований и сопоставимость результатов терапии.
